//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoriaNET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoriaNET.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command does not exist or corresponding module is disabled..
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t do that with date time..
        /// </summary>
        public static string DateTimeIntentNotUnderstood {
            get {
                return ResourceManager.GetString("DateTimeIntentNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        public static string GeneralAt {
            get {
                return ResourceManager.GetString("GeneralAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string GeneralDone {
            get {
                return ResourceManager.GetString("GeneralDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string GeneralFor {
            get {
                return ResourceManager.GetString("GeneralFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not give me coordinates..
        /// </summary>
        public static string LocationModuleCoordinatesNotFound {
            get {
                return ResourceManager.GetString("LocationModuleCoordinatesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location module allows Loria to keep track of people location..
        /// </summary>
        public static string LocationModuleDescription {
            get {
                return ResourceManager.GetString("LocationModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know..
        /// </summary>
        public static string LocationModuleIDontKnow {
            get {
                return ResourceManager.GetString("LocationModuleIDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location module.
        /// </summary>
        public static string LocationModuleName {
            get {
                return ResourceManager.GetString("LocationModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not give me a person..
        /// </summary>
        public static string LocationModulePersonNotFound {
            get {
                return ResourceManager.GetString("LocationModulePersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve never met that person..
        /// </summary>
        public static string LocationModulePersonUnknown {
            get {
                return ResourceManager.GetString("LocationModulePersonUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not give me a place..
        /// </summary>
        public static string LocationModulePlaceNotFound {
            get {
                return ResourceManager.GetString("LocationModulePlaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know this place..
        /// </summary>
        public static string LocationModulePlaceUnknown {
            get {
                return ResourceManager.GetString("LocationModulePlaceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is at.
        /// </summary>
        public static string LocationModulePositionAt {
            get {
                return ResourceManager.GetString("LocationModulePositionAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter.
        /// </summary>
        public static string LocationModulePositionEnter {
            get {
                return ResourceManager.GetString("LocationModulePositionEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leave.
        /// </summary>
        public static string LocationModulePositionLeave {
            get {
                return ResourceManager.GetString("LocationModulePositionLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will remind you to.
        /// </summary>
        public static string ReminderCreateConfirmation {
            get {
                return ResourceManager.GetString("ReminderCreateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to give me a date when the reminder should fire..
        /// </summary>
        public static string ReminderDateNotFound {
            get {
                return ResourceManager.GetString("ReminderDateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You give me a date that I don&apos;t understand..
        /// </summary>
        public static string ReminderDateNotUnderstood {
            get {
                return ResourceManager.GetString("ReminderDateNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t do that with reminder..
        /// </summary>
        public static string ReminderIntentNotUnderstood {
            get {
                return ResourceManager.GetString("ReminderIntentNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to give me a text to remind..
        /// </summary>
        public static string ReminderTextNotFound {
            get {
                return ResourceManager.GetString("ReminderTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VoiceMicrosoftCognitiveServiceApiKeyNotFound {
            get {
                return ResourceManager.GetString("VoiceMicrosoftCognitiveServiceApiKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VoiceMicrosoftLuisApiKeyNotFound {
            get {
                return ResourceManager.GetString("VoiceMicrosoftLuisApiKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VoiceMicrosoftLuisAppIdNotFound {
            get {
                return ResourceManager.GetString("VoiceMicrosoftLuisAppIdNotFound", resourceCulture);
            }
        }
    }
}
